#!/bin/bash -e

srcdir=$(dirname $(readlink -f "$0"))

for ((i = 1;i <= $#;i++)) ;do
    case "${!i}" in
	-p)
	    ((i++))
	    prefix="${!i}"
	    ;;
    esac
done

extension="overview-icon@yyc1992.gmail.com"
usr_dir=/usr

mkdir -p "${prefix}/${usr_dir}/share/gnome-shell/extensions"
cp -vr "${srcdir}/$extension" "${prefix}/${usr_dir}/share/gnome-shell/extensions/"
